version: "3.8"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamo/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: react-flask-app-api
    container_name: api
    depends_on:
      - dynamodb-local
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - APP_ENV=$APP_ENV
    image: react-flask-app-client
    container_name: client
    ports:
      - "3000:80"
