version: "3.8"
services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamo/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - APP_ENV=local
    entrypoint: ["./docker_entrypoint.sh", "run"]
    image: react-flask-app-api
    container_name: api
    depends_on:
      - dynamodb-local
    volumes:
      - ./backend:/app  # bind mount the backend code

  client:
    build:
      context: .
      dockerfile: Dockerfile.client.dev
      args:
        - APP_ENV=local
    image: react-flask-app-client-dev
    container_name: client-dev
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./:/app
