# This Dockerfile builds the Backend only.

FROM python:3.9
WORKDIR /app

COPY /backend/requirements.txt ./requirements.txt
RUN pip3 install -r ./requirements.txt

COPY /backend/ .

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]