# This Dockerfile builds the Backend only.

FROM python:3.9
WORKDIR /app

COPY backend/requirements.txt backend/base.py backend/.flaskenv \
backend/config.py backend/controller.py ./
COPY backend/creatures_folder ./creatures_folder
COPY backend/names_folder ./names_folder
COPY backend/npc_stats ./npc_stats
RUN pip3 install -r ./requirements.txt
ENV FLASK_ENV prod

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "base:app"]