version: "3.8"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamo/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   image: react-flask-app-api
  #   links:
  #     - "dynamodb-local:db"
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   image: react-flask-app-client
  #   ports:
  #     - "3000:80"
